---
title: "Risk Prediction Calculator"
author: "Mariella Gregorich"
date: "14.06.2021"
output: 
  bookdown::word_document2:
    toc: true
    reference_docx: "template.docx"
---


```{r setup, include=FALSE}
rm(list=ls())

pacman::p_load(tidyr, plyr, reshape2, ggplot2, openxlsx, stringr, transplantr, skimr,
               lme4, readxl, purrr, janitor, tableone, dplyr, flextable)


# ------ Initialization 
set.seed(12345)

# Data and Paths
data.path = "../Data/"
GCKD.path = paste0(data.path, "GCKD/")
PROVALID.path = paste0(data.path, "PROVALID/")
out.path = "../Output/"


# ------- Start the fun
source("01_dataprep.R", print.eval=F)

```


```{r}
# Number of subjects per country and cohort
table(data.full[!duplicated(data.full$PatID),]$Cohort)
table(data.full[!duplicated(data.full$PatID),]$Country)


# Distribution of baseline variables between PROVALID and GCKD
data.full %>% 
  filter(Time==0 & Cohort %in% "PROVALID") %>%
  skim()

data.full %>% 
  filter(Time==0 & Cohort %in% "GCKD") %>%
  skim()

tbl <- data.frame(print(CreateTableOne(vars=c(colnames(data.full)[str_detect(colnames(data.full), "BL_")], "FU_eGFR_epi"), strata="Cohort", data=data.full[data.full$Time==0,], test=F)) )
tbl$Variable <- rownames(tbl)

tbl%>%
  relocate(Variable, .before=GCKD) %>%
  flextable() %>%
  autofit()

# Histogram of all baseline variables
data.full %>%
  select(BL_age, BL_gender, BL_bmi, BL_smoking, BL_bpsys, BL_bpdia, BL_hba1c, BL_serumchol, BL_hemo, 
         BL_med_dm, BL_med_bp, BL_med_lipid, BL_uacr, BL_uacr_log2) %>%
  mutate_all(as.numeric) %>%
  gather %>%
  ggplot(aes(value)) + 
  geom_histogram(bins = 50) + 
  facet_wrap(~key, scales = 'free_x') +
  theme_bw()


# Histograms per time point for eGFR
data.full %>% filter(Time==0) %>%  pull(FU_eGFR_epi) %>% hist() 
data.full %>% filter(Time==1) %>%  pull(FU_eGFR_epi) %>% hist() 
data.full %>% filter(Time==2) %>%  pull(FU_eGFR_epi) %>% hist() 
data.full %>% filter(Time==3) %>%  pull(FU_eGFR_epi) %>% hist() 
data.full %>% filter(Time==4) %>%  pull(FU_eGFR_epi) %>% hist() 
data.full %>% filter(Time==5) %>%  pull(FU_eGFR_epi) %>% hist() 
data.full %>% filter(Time==6) %>%  pull(FU_eGFR_epi) %>% hist() 


# ---------- Correlation
x_tmp <- model.matrix(FU_eGFR_epi~BL_age + BL_gender + BL_smoking + BL_bmi + BL_bpsys + BL_bpdia + BL_hba1c 
                      + BL_serumchol + BL_hemo + BL_uacr + BL_med_dm + BL_med_bp + BL_med_lipid, 
                      data=data.full[data.full$Time==0,])[,-1]
corr <- abs(cor(x_tmp))
(corr>0.5)


# --------- Missingness
data.full <- data.full[complete.cases(data.full),]

```


